[package]
name = "blaim-web"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { version = "0.14.0", features = ["serde_json"] }
axum = { version = "0.8.4", features = ["macros", "tracing"] }
tokio.workspace = true
sqlx.workspace = true
tower-http = { version = "0.6.6", features = ["fs", "trace", "tracing"] }
tracing-subscriber = "0.3.20"
tracing = "0.1.41"
blaim-db ={ path="../blaim-db" }
color-eyre.workspace = true
futures = "0.3.31"
rand = "0.9.2"
tower-sessions = "0.14.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["postgres"] }
reqwest = { version = "0.12.23", features = ["json"] }
time.workspace = true
serde.workspace = true
serde_json = "1.0.145"
